<?php
/*
 * Perceptual image-hash blacklist.
 *
 * Unlike an exact file hash (md5/sha1), a perceptual hash changes only slightly when the
 * image changes slightly, so a near-duplicate (re-encoded, resized, one pixel altered)
 * still produces a hash within a small Hamming distance of the original. On upload we
 * hash the image and reject it if it lands within $config['image_hash']['threshold'] of
 * any blacklisted hash.
 *
 * The blacklist (`image_hashes` table) tags every entry with the algorithm that produced
 * it, so hashes generated by other tools can be imported and matched, as long as the
 * algorithm is one we can also compute here.
 */

defined('TINYBOARD') or exit;

/**
 * Supported algorithms.
 *  - perceptual: derived from the decoded image; compared by Hamming distance.
 *  - exact:      derived from the raw file bytes; must match exactly (distance 0).
 */
function image_hash_algos() {
	return [
		'phash'  => [ 'type' => 'perceptual', 'bits' => 64 ],  // DCT based, most robust
		'dhash'  => [ 'type' => 'perceptual', 'bits' => 64 ],  // gradient based
		'ahash'  => [ 'type' => 'perceptual', 'bits' => 64 ],  // average based
		'md5'    => [ 'type' => 'exact',      'bits' => 128 ],
		'sha1'   => [ 'type' => 'exact',      'bits' => 160 ],
		'sha256' => [ 'type' => 'exact',      'bits' => 256 ],
	];
}

/* ------------------------------------------------------------------ bit utils */

function image_hash_bits_to_hex($bits) {
	// Pad to a multiple of 4 bits so the final nibble is well defined.
	if (strlen($bits) % 4 !== 0) {
		$bits = str_pad($bits, strlen($bits) + (4 - strlen($bits) % 4), '0');
	}
	$hex = '';
	for ($i = 0, $n = strlen($bits); $i < $n; $i += 4) {
		$hex .= dechex(bindec(substr($bits, $i, 4)));
	}
	return $hex;
}

/**
 * Hamming distance between two equal-length hex strings (number of differing bits).
 * Returns -1 when the strings are not comparable (different length).
 */
function image_hash_hamming($a, $b) {
	static $pop = null;
	if ($pop === null) {
		$pop = [];
		for ($i = 0; $i < 16; $i++) {
			$pop[$i] = substr_count(decbin($i), '1');
		}
	}

	$a = strtolower($a);
	$b = strtolower($b);
	if (strlen($a) !== strlen($b)) {
		return -1;
	}

	$dist = 0;
	for ($i = 0, $n = strlen($a); $i < $n; $i++) {
		$x = hexdec($a[$i]) ^ hexdec($b[$i]);
		$dist += $pop[$x & 0xF];
	}
	return $dist;
}

/* --------------------------------------------------------------- image decode */

/** Decode an image file to a GD resource, or null on failure. */
function image_hash_load($path) {
	if (!function_exists('imagecreatefromstring')) {
		return null;
	}
	$data = @file_get_contents($path);
	if ($data === false) {
		return null;
	}
	$im = @imagecreatefromstring($data);
	return $im ?: null;
}

/** Downscale to $w x $h and return a row-major matrix of luma values (floats). */
function image_hash_gray($im, $w, $h) {
	$small = imagecreatetruecolor($w, $h);
	// Flatten any transparency onto white so alpha does not skew the luma.
	imagealphablending($small, false);
	imagefilledrectangle($small, 0, 0, $w - 1, $h - 1, imagecolorallocate($small, 255, 255, 255));
	imagealphablending($small, true);
	imagecopyresampled($small, $im, 0, 0, 0, 0, $w, $h, imagesx($im), imagesy($im));

	$m = [];
	for ($y = 0; $y < $h; $y++) {
		$row = [];
		for ($x = 0; $x < $w; $x++) {
			$rgb = imagecolorat($small, $x, $y);
			$r = ($rgb >> 16) & 0xFF;
			$g = ($rgb >> 8) & 0xFF;
			$b = $rgb & 0xFF;
			$row[] = 0.299 * $r + 0.587 * $g + 0.114 * $b;
		}
		$m[] = $row;
	}
	imagedestroy($small);
	return $m;
}

/* --------------------------------------------------------- perceptual hashes */

function image_hash_ahash($im) {
	$m = image_hash_gray($im, 8, 8);
	$sum = 0;
	foreach ($m as $row) {
		foreach ($row as $v) {
			$sum += $v;
		}
	}
	$avg = $sum / 64;
	$bits = '';
	foreach ($m as $row) {
		foreach ($row as $v) {
			$bits .= ($v >= $avg) ? '1' : '0';
		}
	}
	return image_hash_bits_to_hex($bits);
}

function image_hash_dhash($im) {
	// 9 wide so each of the 8 columns can be compared with its right neighbour.
	$m = image_hash_gray($im, 9, 8);
	$bits = '';
	for ($y = 0; $y < 8; $y++) {
		for ($x = 0; $x < 8; $x++) {
			$bits .= ($m[$y][$x] < $m[$y][$x + 1]) ? '1' : '0';
		}
	}
	return image_hash_bits_to_hex($bits);
}

function image_hash_phash($im) {
	$N = 32;
	$m = image_hash_gray($im, $N, $N);

	// Cosine table for an N-point DCT-II.
	static $cos_cache = [];
	if (!isset($cos_cache[$N])) {
		$c = [];
		for ($u = 0; $u < $N; $u++) {
			for ($x = 0; $x < $N; $x++) {
				$c[$u][$x] = cos((2 * $x + 1) * $u * M_PI / (2 * $N));
			}
		}
		$cos_cache[$N] = $c;
	}
	$C = $cos_cache[$N];

	// Only the top-left 8x8 low-frequency coefficients are needed.
	$dct = [];
	for ($u = 0; $u < 8; $u++) {
		for ($v = 0; $v < 8; $v++) {
			$sum = 0.0;
			for ($y = 0; $y < $N; $y++) {
				$cvy = $C[$v][$y];
				$row = $m[$y];
				for ($x = 0; $x < $N; $x++) {
					$sum += $row[$x] * $C[$u][$x] * $cvy;
				}
			}
			$dct[$u][$v] = $sum; // scale factors are irrelevant to the median comparison
		}
	}

	// Median of the low-frequency block, excluding the DC term which dominates.
	$vals = [];
	for ($u = 0; $u < 8; $u++) {
		for ($v = 0; $v < 8; $v++) {
			if ($u === 0 && $v === 0) {
				continue;
			}
			$vals[] = $dct[$u][$v];
		}
	}
	sort($vals);
	$n = count($vals);
	$median = ($n % 2) ? $vals[($n - 1) / 2] : ($vals[$n / 2 - 1] + $vals[$n / 2]) / 2;

	$bits = '';
	for ($u = 0; $u < 8; $u++) {
		for ($v = 0; $v < 8; $v++) {
			$bits .= ($dct[$u][$v] > $median) ? '1' : '0';
		}
	}
	return image_hash_bits_to_hex($bits);
}

/**
 * Compute a hash of the given algorithm. Perceptual algorithms use the GD image ($im),
 * exact algorithms use the file at $path. Returns a lowercase hex string, or null.
 */
function image_hash_compute($algo, $im, $path) {
	switch ($algo) {
		case 'phash':  return $im ? image_hash_phash($im) : null;
		case 'dhash':  return $im ? image_hash_dhash($im) : null;
		case 'ahash':  return $im ? image_hash_ahash($im) : null;
		case 'md5':    return $path ? md5_file($path) : null;
		case 'sha1':   return $path ? sha1_file($path) : null;
		case 'sha256': return $path ? hash_file('sha256', $path) : null;
		default:       return null;
	}
}

/** Compute a single algorithm's hash of a file (used by the admin "ban this image" flow). */
function image_hash_compute_file($algo, $path) {
	$algos = image_hash_algos();
	if (!isset($algos[$algo])) {
		return null;
	}
	if ($algos[$algo]['type'] === 'perceptual') {
		$im = image_hash_load($path);
		if (!$im) {
			return null;
		}
		$hash = image_hash_compute($algo, $im, $path);
		imagedestroy($im);
		return $hash;
	}
	return image_hash_compute($algo, null, $path);
}

/* --------------------------------------------------------------- blacklist DB */

/** Load the blacklist grouped by algorithm, memoised for the request. */
function image_hash_load_bans() {
	static $cache = null;
	if ($cache !== null) {
		return $cache;
	}

	$out = [];
	try {
		$query = query("SELECT `algo`, `hash`, `bits`, `note` FROM ``image_hashes``");
	} catch (PDOException $e) {
		$query = false; // table absent on installs predating this feature
	}
	if ($query) {
		foreach ($query->fetchAll(PDO::FETCH_ASSOC) as $row) {
			$out[$row['algo']][] = $row;
		}
	}

	$cache = $out;
	return $out;
}

/**
 * Return the closest matching blacklist entry for the image at $path, or null.
 * The returned array is the DB row plus 'distance' and 'algo'.
 */
function image_hash_find_match($config, $path) {
	$bans = image_hash_load_bans();
	if (empty($bans)) {
		return null;
	}

	$algos = image_hash_algos();
	$threshold = (int)$config['image_hash']['threshold'];

	// Only decode the image once, and only if a perceptual algorithm is in use.
	$need_image = false;
	foreach ($bans as $algo => $list) {
		if (isset($algos[$algo]) && $algos[$algo]['type'] === 'perceptual') {
			$need_image = true;
			break;
		}
	}
	$im = $need_image ? image_hash_load($path) : null;

	$best = null;
	foreach ($bans as $algo => $list) {
		if (!isset($algos[$algo])) {
			continue;
		}
		$hash = image_hash_compute($algo, $im, $path);
		if ($hash === null) {
			continue;
		}
		$max = ($algos[$algo]['type'] === 'exact') ? 0 : $threshold;

		foreach ($list as $row) {
			$candidate = strtolower($row['hash']);
			if (strlen($candidate) !== strlen($hash)) {
				continue;
			}
			$dist = image_hash_hamming($hash, $candidate);
			if ($dist < 0 || $dist > $max) {
				continue;
			}
			if ($best === null || $dist < $best['distance']) {
				$best = $row;
				$best['distance'] = $dist;
				$best['algo'] = $algo;
			}
		}
	}

	if ($im) {
		imagedestroy($im);
	}
	return $best;
}

/**
 * Insert one blacklist entry. Returns true if a new row was added (false if invalid or a
 * duplicate). Deduplicated by (algo, hash) via INSERT IGNORE.
 */
function image_hash_insert($algo, $hash, $note) {
	$algos = image_hash_algos();
	$algo = strtolower(trim($algo));
	$hash = strtolower(trim($hash));

	if (!isset($algos[$algo]) || $hash === '' || !ctype_xdigit($hash)) {
		return false;
	}

	$query = prepare("INSERT IGNORE INTO ``image_hashes`` (`algo`, `hash`, `bits`, `note`, `created`) VALUES (:algo, :hash, :bits, :note, :created)");
	$query->bindValue(':algo', $algo);
	$query->bindValue(':hash', $hash);
	$query->bindValue(':bits', strlen($hash) * 4, PDO::PARAM_INT);
	$query->bindValue(':note', $note);
	$query->bindValue(':created', time(), PDO::PARAM_INT);
	$query->execute() or error(db_error($query));

	return $query->rowCount() > 0;
}
